import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const lexend = localFont({
  src:'/fonts/Lexend-Regular.ttf',
});

const cunia = localFont({
  src:'/fonts/Cunia.ttf',
  variable: "--font-cunia"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} 
        ${cunia.variable} antialiased bg-slate-50`}
      >
        <Header/>
        <main className="min-h-svh">
        {children}
        </main>
      </body>
    </html>
  );
}
